blueprints/user/models.py
from blueprints import db

commantaire_maison = db.Table('user_like',
    db.Column('utilisateur_id', db.Integer, db.ForeignKey('utilisateur.id')),
    db.Column('commentaire_maison_id', db.Integer, db.ForeignKey('commentaire_maison.id'))
) 

class Utilisateur(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    nom = db.Column(db.String(20))
    prenom = db.Column(db.String(70))
    mail = db.Column(db.Text)
    tel = db.Column(db.Integer)
    password = db.Column(db.Text)
    photo = db.Column(db.Text) 
    utilisateur_commentaire = db.relationship("Commentaire_site",uselist=True)

    def __init__(self):
        pass

    def __repr__(self):
        return str(self.nom)

class Agence(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    nom = db.Column(db.String(20))
    photo = db.Column(db.Text) 
    tel = db.Column(db.Text)
    mail = db.Column(db.Text)
    nonSite = db.Column(db.Text)
    urlSite = db.Column(db.Text)
    agence_maison = db.relationship("Maison",uselist=True)

    def __init__(self):
        pass

    def __repr__(self):
        return str(self.nom)

class Categorie(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    titre = db.Column(db.Text)
    categirie_maison = db.relationship("Maison",uselist=True)

    def __init__(self):
        pass

    def __repr__(self):
        return str(self.titre)

class Maison(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    titre = db.Column(db.Text)
    photo = db.Column(db.Text)
    description = db.Column(db.Text)
    longitude = db.Column(db.Integer)
    lartitude = db.Column(db.Integer)
    prix = db.Column(db.Text)
    Agence_id = db.Column(db.Integer, db.ForeignKey('agence.id'))
    Categorie_id = db.Column(db.Integer, db.ForeignKey('categorie.id'))
    maison_image = db.relationship("Image",uselist=True)
    maison_categorie = db.relationship("Categorie",uselist=True)

    def __init__(self):
        pass

    def __repr__(self):
        return str(self.titre)

class Image(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    nom = db.Column(db.Text)
    Maison_id = db.Column(db.Integer, db.ForeignKey('maison.id'))
    image_maison = db.relationship("Maison",uselist=True)

    def __init__(self):
        pass

    def __repr__(self):
        return str(self.nom)

class Commentaire_site(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    contenue = db.Column(db.Text)
    Utilisateur_id = db.Column(db.Integer, db.ForeignKey('utilisateur.id'))

    def __init__(self):
        pass

    def __repr__(self):
        return str(self.id)

class Commentaire_maison(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    contenue = db.Column(db.Text)
    Utilisateur_id = db.Column(db.Integer, db.ForeignKey('utilisateur.id'))
    like = db.relationship('Utilisateur', secondary=commantaire_maison, lazy='subquery',backref=db.backref('commentaire_maison', lazy='dynamic'))
    

    def __init__(self):
        pass

    def __repr__(self):
        return str(self.id)

blueprints/user/views.py
import os
import re
import datetime
from flask import Blueprint,render_template, url_for, request , redirect,session,Response,request
from wtforms import form
from blueprints import db
from blueprints.user.models import Maison,Commentaire_site,Utilisateur
from blueprints.user.form import Form_commentaire_site,Form_connexion,Form_inscription
from werkzeug.utils import secure_filename

user = Blueprint('user',__name__,template_folder='templates/user',static_folder='static')

#fonction qui retourne le premier prenom
def AvoirPrenom(user):
    listeprenom= user.prenom.split()
    return listeprenom[0].upper()


#Acceuil pour utilisateur
@user.route('')
def home():
    maisons = Maison.query.order_by(Maison.id).limit(3).all()
    commentaires = Commentaire_site.query.order_by(Commentaire_site.id).all()
    form = Form_commentaire_site()
    return render_template('Acceuil.htm',maisons=maisons,commentaires=commentaires,form=form)

#Liste de toutes les maisons disponibles
@user.route('/maisons')
def maisons():
    maisons = Maison.query.order_by(Maison.id).all()
    form = Form_commentaire_site()
    return render_template('Maison.html',maisons=maisons,form=form)

#Contact du site
@user.route('/contact')
def contact():
    return render_template('contact.html')

#Consulter detail de maison
@user.route('/detail/<int:id>')
def detail(id):
    maison = Maison.query.get(id)
    maisons = Maison.query.order_by(Maison.id).all()
    form = Form_commentaire_site()
    return render_template('Detailmaison.html', maison=maison,form=form,maisons=maisons)

#Visite 3d
@user.route('/vue/<int:id>')
def vue(id):
    maison = Maison.query.get(id)
    return render_template('view.html',maison=maison)

#connection
@user.route('/connection',methods = ['get','post'])
def connection():
    form = Form_connexion()
    email= form.mail.data
    personne = Utilisateur.query.filter_by(mail=email).first()
    if form.validate_on_submit() and form.password.data == personne.password :
        preprenom = AvoirPrenom(personne)
        session['user'] = {
                'id':personne.id,
                'nom':personne.nom,
                'prenom':preprenom,
            }
        return redirect(url_for('user.home'))
    return render_template('connection.html',form=form)


#Inscription
@user.route('/inscription',methods = ['get','post'])
def inscription():
    form = Form_inscription()
    if form.validate_on_submit():
        personne  = Utilisateur()
        personne.mail = form.mail.data
        personne.tel = int(form.tel.data)
        personne.nom = form.nom.data
        personne.prenom = form.prenom.data
        personne.password = form.password.data
        db.session.add(personne)
        db.session.commit()
        preprenom = AvoirPrenom(personne)
        session['user'] = {
                'id':personne.id,
                'nom':personne.nom,
                'prenom':preprenom,
            }
        return redirect(url_for('user.home'))
    return render_template('Inscription.html',form=form)

#route de profile
@user.route('/profile')
def profile():
    try:
        print(session['user'])
    except:
        return redirect(url_for('user.connection'))
    user = Utilisateur.query.get(session['user']['id'])
    return render_template('profile.html',user = user)


#route de deconnection
@user.route('deconnection')
def deconnection():
    del session['user']
    return redirect(url_for('user.home'))

#route pour contacter le site
@user.route('/envoi',methods = ['post'])
def envoi():
    try:
        print(session['user'])
    except:
        return redirect(url_for('user.connection'))
    form = Form_commentaire_site()
    if form.validate_on_submit():
        commentaire=Commentaire_site()
        commentaire.contenue = form.contenu.data
        commentaire.Utilisateur_id = session['user']['id']
        db.session.add(commentaire)
        db.session.commit()
        return redirect(url_for('user.home'))

blueprints/user/templates/user/Acceuil.htm
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@100;200;300;400;500;600;700;800;900&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{{ url_for('user.static',filename='style/styleAc.css') }}">
    <title>Document</title>
</head>
<body>
<!-- Menu responsible -->
    <div class="vol">
        <img src="{{ url_for('user.static',filename='image/icons8-plus-30.png') }}" alt="b">
        <div class="user">
            <img src="{{ url_for('user.static',filename='image/icons8-utilisateur-24.png') }}" alt="user">
            <p>{% if session['user'] %}<a href="{{ url_for('user.profile') }}">{{session['user']['nom'] | upper}} {{session['user']['prenom'] | upper}}</a> {% else %} <a href="{{ url_for('user.connection') }}">User</a>{% endif %}</p>
        </div>
        <ul>
            <li><a href="{{ url_for('user.home') }}" class="actif">Acceuil</a></li>
            <li><a href="{{ url_for('user.maisons') }}">Maisons</a></li>
            <li><a href="{{ url_for('user.contact') }}">Contact</a></li>
        </ul>    
    </div>

<!-- header  -->

    <div class="dessus">
        <h2>LOGO</h2>
        <img src="{{ url_for('user.static',filename='/image/icons8-menu-arrondi-50.png') }}" alt="">
        <form action="">
            <input type="search" name="" id=""></p>
            <img src="{{ url_for('user.static',filename='image/icons8-chercher-24.png') }}" for="search" alt="coco">
            <input type="submit" value="" id="search" style="display: none;">
        </form>
        <div class="user">
            <img src="{{ url_for('user.static',filename='image/icons8-utilisateur-24.png') }}" alt="user">
            <p>{% if session['user'] %}<a href="{{ url_for('user.profile') }}">{{session['user']['nom'] | upper}} {{session['user']['prenom'] | upper}}</a> {% else %} <a href="{{ url_for('user.connection') }}">User</a>{% endif %}</p>
        </div>
    </div>

<!-- Menu de navigation -->

    <ul class="grand">
        <li><a href="{{ url_for('user.home') }}" class="actif">Acceuil</a></li>
        <li><a href="{{ url_for('user.maisons') }}">Maisons</a></li>
        <li><a href="{{ url_for('user.contact') }}">Contact</a></li>
    </ul>
    
<!-- presentation de la visite 3d  -->

    <div class="decouvert">
        <div class="color_background"> </div>
        <div class="info">
            <h1>Visite Virtuelle</h1>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse tincidunt interdum tincidunt. Integer ac pretium nisl. Donec at ante sit amet orci ullamcorper fermentum eu ac dolor</p>
        </div>
    </div>

<!-- section contenant les maisons -->

    <section>
        <h2>Nos Maisons</h2>
        {% for maison in maisons %}
        <article>
            <div class="image">
                <img src="{{ url_for('admin.static',filename='uploads/'+maison.titre+'/'+maison.photo) }}" alt="maison">
                <div class="vole">
                    <div class="haut">A louer</div>
                    <div class="prix"> {{maison.prix}} fcfa</div>
                </div>
            </div>
            <div class="article_info">
                <div class="agence"><img src="{{ url_for('user.static',filename='image/icons8-utilisateur-24.png') }}" alt="Agence"><p>Agence</p></div>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit.</p>
                <div class="lieu"><div><img src="{{ url_for('user.static',filename='image/icons8-location-64.png') }}" alt="lieu"><p>{{ maison.longitude }}-{{ maison.lartitude }}</p></div><p><a href="{{ url_for('user.detail',id=maison.id) }}">Voir Plus</a></p></div>
            </div>
        </article>
        {% endfor %}
        <div class="btn"><a href="">Voir PLus</a></div>
    </section>

<!-- section des commentaires sur le site -->
    <section>
        <h2>Nos Internautes</h2>
        {% for commentaire in commentaires %}
        <div class="conteneur">
            <img src="{{ url_for('user.static',filename='image/pexels-max-vakhtbovych-8134848.jpg') }}" alt="">
            <h3>N'da Marion</h3>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Voluptates, eligendi?</p>
        </div>
        {% endfor %}
    </section>
    

<!-- section des info sur le site -->

    <div class="avant_foot">
        <div class="color_background"></div>
        <div class="info_foot">
            <h1>LOGO</h1>
            <div class="contact">
                <h3>Contact</h3>
                <p>Mail :HomeSearch@gmail.com</p>
                <p>Tel :0748569941/0546283701</p>
                <p>Localisation : Abidjan zone 4</p>
            </div>
            <form action="{{ url_for('user.envoi') }}" method="POST">
                {{form.hidden_tag()}}
                <h3>Commentaire</h3>
                <p>{{form.contenu}}</p>
                <p>{{form.submit}}</p>
            </form>
        </div>
    </div>

<!-- footer -->

    <footer>
        <p><a href="#"><img src="{{ url_for('user.static',filename='image/icons8-f-de-facebook-30.png') }}" alt="facebook"></a></p>
        <p><a href="#"><img src="{{ url_for('user.static',filename='image/icons8-instagram-30.png') }}" alt="insta"></a></p>
        <p><a href="#"><img src="{{ url_for('user.static',filename='image/icons8-twitter-30.png') }}" alt="twinter"></a></p>
    </footer>
    <script src="{{ url_for('user.static', filename='Js/menu.js') }}"></script>
</body>
</html>

blueprints/user/templates/user/Detailmaison.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@100;200;300;400;500;600;700;800;900&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="../static/style/StyleDe.css">
</head>
<body>
    <!-- Menu responsible -->
    <div class="vol">
        <img src="{{ url_for('user.static',filename='image/icons8-plus-30.png') }}" alt="b">
        <div class="user">
            <img src="{{ url_for('user.static',filename='image/icons8-utilisateur-24.png') }}" alt="user">
            <p>{% if session['user'] %}<a href="{{ url_for('user.profile') }}">{{session['user']['nom'] | upper}} {{session['user']['prenom'] | upper}}</a> {% else %} <a href="{{ url_for('user.connection') }}">User</a>{% endif %}</p>
        </div>
        <ul>
            <li><a href="{{ url_for('user.home') }}" class="actif">Acceuil</a></li>
            <li><a href="{{ url_for('user.maisons') }}">Maisons</a></li>
            <li><a href="{{ url_for('user.contact') }}">Contact</a></li>
        </ul>    
    </div>

    <!-- header  -->

    <div class="dessus">
        <h2>LOGO</h2>
        <img src="{{ url_for('user.static',filename='/image/icons8-menu-arrondi-50.png') }}" alt="">
        <form action="">
            <input type="search" name="" id=""></p>
            <img src="{{ url_for('user.static',filename='image/icons8-chercher-24.png') }}" for="search" alt="coco">
            <input type="submit" value="" id="search" style="display: none;">
        </form>
        <div class="user">
            <img src="{{ url_for('user.static',filename='image/icons8-utilisateur-24.png') }}" alt="user">
            <p>{% if session['user'] %}<a href="{{ url_for('user.profile') }}">{{session['user']['nom'] | upper}} {{session['user']['prenom'] | upper}}</a> {% else %} <a href="{{ url_for('user.connection') }}">User</a>{% endif %}</p>
        </div>
    </div>

    <!-- Menu de navigation -->

    <ul class="grand">
        <li><a href="{{ url_for('user.home') }}" class="actif">Acceuil</a></li>
        <li><a href="{{ url_for('user.maisons') }}">Maisons</a></li>
        <li><a href="{{ url_for('user.contact') }}">Contact</a></li>
    </ul>

    <section class="apropros">
        <div class="gauche">
            <p><a href="{{ url_for('user.vue',id=maison.id) }}"><img src="../static/image/icons8-3d-50 (1).png" alt="">Visualiser</a></p>
            <div class="prix">
                <h3>Prix</h3>
                <p>{{ maison.prix }} fcfa</p>
            </div>
            <div class="b">
                <h3>Plus De Detail</h3>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Quia, reprehenderit sequi aperiam cupiditate quis pariatur.</p>
            </div>
            <div class="info_agence">
                <h3>Agence</h3>
                <div class="dedans">
                    <div>
                        <img src="../static/image/icons8-utilisateur-24 (1).png" alt="agence">
                        <h4>Nom</h4>
                    </div>
                    <div class="agence_contact">
                        <p><img src="../static/image/icons8-téléphone-30 (1).png" alt="">074659941</p>
                        <p><img src="../static/image/icons8-fenêtre-dapplication-50.png" alt="">Siteagence.com</p>
                        <p><img src="../static/image/icons8-courrier-24.png" alt="">Mailagencegamil.com</p>
                    </div>
                    <p><a href="#">Prendre rendez-vous</a></p>
                </div>
            </div>
        </div>
        <div class="droit">
            <img src="{{ url_for('admin.static',filename='uploads/'+maison.titre+'/'+maison.photo) }}" alt="maison">
            <div class="descrisption">
                <h3>Description De La Maison</h3>
                <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Quo, iusto dolore sit veniam quam mollitia nulla incidunt nam deleniti, vero consequuntur sapiente accusamus. Aspernatur, fugit dolor eos itaque dolorum nisi.</p>
            </div>
            <div class="maison_lieu">
                <h3>Localisation</h3>
                <img src="../static/image/GoogleMapTA.jpg" alt="">
            </div>
        </div>
    </section>
    <section class="avis">
        <h2>Avis Du Voisinage</h2>
        <div class="conteneur">
            <img src="../static/image/pexels-max-vakhtbovych-8134848.jpg" alt="">
            <h3>N'da Marion</h3>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Voluptates, eligendi?</p>
        </div>
        <div class="conteneur">
            <img src="../static/image/pexels-max-vakhtbovych-8134848.jpg" alt="">
            <h3>N'da Marion</h3>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Voluptates, eligendi?</p>
        </div>
        <div class="conteneur">
            <img src="../static/image/pexels-max-vakhtbovych-8134848.jpg" alt="">
            <h3>N'da Marion</h3>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Voluptates, eligendi?</p>
        </div>
    </section>
    <section class="plus_maisons">
        <h2>Nos Maisons</h2>
        {% for maiso in maisons %}
        <article>
            <div class="image">
                <img src="{{ url_for('admin.static',filename='uploads/'+maiso.titre+'/'+maiso.photo) }}" alt="maison">
                <div class="vole">
                    <div class="haut">A louer</div>
                    <div class="prix"> {{maiso.prix}} fcfa</div>
                </div>
            </div>
            <div class="article_info">
                <div class="agence"><img src="{{ url_for('user.static',filename='image/icons8-utilisateur-24.png') }}" alt="Agence"><p>Agence</p></div>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit.</p>
                <div class="lieu"><div><img src="{{ url_for('user.static',filename='image/icons8-location-64.png') }}" alt="lieu"><p>{{ maiso.longitude }}-{{ maiso.lartitude }}</p></div><p><a href="{{ url_for('user.detail',id=maiso.id) }}">Voir Plus</a></p></div>
            </div>
        </article>
        {% endfor %}
    </section>
    <div class="avant_foot">
        <div class="color_background"></div>
        <div class="info_foot">
            <h1>LOGO</h1>
            <div class="contact">
                <h3>Contact</h3>
                <p><span>Mail :</span> HomeSearch@gmail.com</p>
                <p><span>Tel :</span> 0748569941/0546283701</p>
                <p><span>Localisation :</span> Abidjan zone 4</p>
            </div>
            <form action="{{ url_for('user.envoi') }}" method="POST">
                {{form.hidden_tag()}}
                <h3>Commentaire</h3>
                <p>{{form.contenu(cols="40",rows="10")}}</p>
                <p>{{form.submit}}</p>
            </form>
        </div>
    </div>
    <footer>
        <p><a href="#"><img src="../static/image/icons8-f-de-facebook-30.png" alt="facebook"></a></p>
        <p><a href="#"><img src="../static/image/icons8-instagram-30.png" alt="insta"></a></p>
        <p><a href="#"><img src="../static/image/icons8-twitter-30.png" alt="twinter"></a></p>
    </footer>
    <script src="{{ url_for('user.static', filename='js/menu.js') }}"></script>
</body>
</html>

blueprints/user/templates/user/Maison.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@100;200;300;400;500;600;700;800;900&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{{ url_for('user.static',filename='style/styleMa.css') }}">
</head>
<body>
    <!-- Menu responsible -->
    <div class="vol">
        <img src="{{ url_for('user.static',filename='image/icons8-plus-30.png') }}" alt="b">
        <div class="user">
            <img src="{{ url_for('user.static',filename='image/icons8-utilisateur-24.png') }}" alt="user">
            <p>{% if session['user'] %}<a href="{{ url_for('user.profile') }}">{{session['user']['nom'] | upper}} {{session['user']['prenom'] | upper}}</a> {% else %} <a href="{{ url_for('user.connection') }}">User</a>{% endif %}</p>
        </div>
        <ul>
            <li><a href="{{ url_for('user.home') }}" class="actif">Acceuil</a></li>
            <li><a href="{{ url_for('user.maisons') }}">Maisons</a></li>
            <li><a href="{{ url_for('user.contact') }}">Contact</a></li>
        </ul>    
    </div>

<!-- header  -->

    <div class="dessus">
        <h2>LOGO</h2>
        <img src="{{ url_for('user.static',filename='/image/icons8-menu-arrondi-50.png') }}" alt="">
        <form action="">
            <input type="search" name="" id=""></p>
            <img src="{{ url_for('user.static',filename='image/icons8-chercher-24.png') }}" for="search" alt="coco">
            <input type="submit" value="" id="search" style="display: none;">
        </form>
        <div class="user">
            <img src="{{ url_for('user.static',filename='image/icons8-utilisateur-24.png') }}" alt="user">
            <p>{% if session['user'] %}<a href="{{ url_for('user.profile') }}">{{session['user']['nom'] | upper}} {{session['user']['prenom'] | upper}}</a> {% else %} <a href="{{ url_for('user.connection') }}">User</a>{% endif %}</p>
        </div>
    </div>

    <ul class="grand">
        <li><a href="{{ url_for('user.home') }}" class="actif">Acceuil</a></li>
        <li><a href="{{ url_for('user.maisons') }}">Maisons</a></li>
        <li><a href="{{ url_for('user.contact') }}">Contact</a></li>
    </ul>   
    <div class="decouvert">
        <div class="color_background"> </div>
        <div class="info">
            <h1>Chalais</h1>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse tincidunt interdum tincidunt. Integer ac pretium nisl. Donec at ante sit amet orci ullamcorper fermentum eu ac dolor</p>
            <div class="btn"><a href="#">Voir plus</a></div>
        </div>
    </div>
    <div class="contener">
        <div class="filtre" style="display: none;">
            <img src="{{ url_for('user.static',filename='image/icons8-paramètres-30.png') }}" alt="">
            <p>Filtrer</p> 
        </div>
        <!-- section contenant les maisons -->

        <section>
            <h2>Nos Maisons</h2>
            {% for maison in maisons %}
            <article>
                <div class="image">
                    <img src="{{ url_for('admin.static',filename='uploads/'+maison.titre+'/'+maison.photo) }}" alt="maison">
                    <div class="vole">
                        <div class="haut">A louer</div>
                        <div class="prix"> {{maison.prix}} fcfa</div>
                    </div>
                </div>
                <div class="article_info">
                    <div class="agence"><img src="{{ url_for('user.static',filename='image/icons8-utilisateur-24.png') }}" alt="Agence"><p>Agence</p></div>
                    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit.</p>
                    <div class="lieu"><div><img src="{{ url_for('user.static',filename='image/icons8-location-64.png') }}" alt="lieu"><p>{{ maison.longitude }}-{{ maison.lartitude }}</p></div><p><a href="{{ url_for('user.detail',id=maison.id) }}">Voir Plus</a></p></div>
                </div>
            </article>
            {% endfor %}
        </section>
    </div>
    <div class="avant_foot">
        <div class="color_background"></div>
        <div class="info_foot">
            <h1>LOGO</h1>
            <div class="contact">
                <h3>Contact</h3>
                <p><span>Mail :</span> HomeSearch@gmail.com</p>
                <p><span>Tel :</span> 0748569941/0546283701</p>
                <p><span>Localisation :</span> Abidjan zone 4</p>
            </div>
            <form action="{{ url_for('user.envoi') }}" method="POST">
                {{form.hidden_tag()}}
                <h3>Commentaire</h3>
                <p>{{form.contenu(cols="40",rows="10")}}</p>
                <p>{{form.submit}}</p>
            </form>
        </div>
    </div>
    <footer>
        <p><a href="#"><img src="{{ url_for('user.static',filename='image/icons8-f-de-facebook-30.png') }}" alt="facebook"></a></p>
        <p><a href="#"><img src="{{ url_for('user.static',filename='image/icons8-instagram-30.png') }}" alt="insta"></a></p>
        <p><a href="#"><img src="{{ url_for('user.static',filename='image/icons8-twitter-30.png') }}" alt="twinter"></a></p>
    </footer>
    <script src="{{ url_for('user.static', filename='js/menu.js') }}"></script>
</body>
</html>

blueprints/user/templates/user/connection.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@100;200;300;400;500;600;700;800;900&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{{ url_for('user.static',filename='/style/connexion.css') }}">
    <title>Document</title>
</head >
<body >
    <h1>Connexion</h1>
    <div class="contener">
        <form action="" method="post">
            {{form.hidden_tag()}}
            <h1>Bienvenue</h1>
            <div><img src="{{ url_for('user.static',filename='/image/icons8-mail-24.png') }}" alt="b">{{ form.mail(placeholder='Mail') }}</div>
            <div><img src="{{ url_for('user.static',filename='/image/icons8-verrouiller-2-26.png') }}" alt="b">{{ form.password(placeholder='Mots de passe') }}</div>
            <p>{{form.submit}}</p>
        </form>
        <div>
            <h2>Inscription</h2>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Aspernatur, excepturi eveniet perspiciatis voluptatem atque possimus.</p>
            <div><a href="{{ url_for('user.inscription') }}">Passer</a></div>
        </div>
    </div>
</body>
</html>